{{- if .Values.webhook.enabled }}
# Certificate for the webhook server TLS
# This requires cert-manager to be installed in the cluster
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.extension.name }}-webhook-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.extension.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: webhook
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: {{ .Values.extension.name }}-webhook-cert
  dnsNames:
    - {{ .Values.webhook.serviceName | default (printf "%s-webhook" .Values.extension.name) }}
    - {{ .Values.webhook.serviceName | default (printf "%s-webhook" .Values.extension.name) }}.{{ .Release.Namespace }}
    - {{ .Values.webhook.serviceName | default (printf "%s-webhook" .Values.extension.name) }}.{{ .Release.Namespace }}.svc
    - {{ .Values.webhook.serviceName | default (printf "%s-webhook" .Values.extension.name) }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ .Values.extension.name }}-selfsigned-issuer
    kind: Issuer
---
# Self-signed issuer for the webhook certificate
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.extension.name }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.extension.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: webhook
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selfSigned: {}
{{- end }}
