{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhook.serviceName | default (printf "%s-webhook" .Values.extension.name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.extension.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: webhook
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: {{ .Values.webhook.port }}
      targetPort: webhook
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.extension.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
